spring:
  application:
    name: product-service
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
server:
  port: 8038
feign:
  client:
    config:
      product-service:
        logger-level: BASIC
        connect-timeout: 5000
        read-timeout: 6000
